# Generated by Django 4.2.14 on 2024-07-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='persons',
            field=models.CharField(max_length=100),
        ),
    ]
