# Generated by Django 4.2.14 on 2024-07-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0003_alter_booking_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
