# Generated by Django 4.2.14 on 2024-07-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0004_booking_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reject',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
