# Generated by Django 4.2.14 on 2024-07-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0005_booking_reject_alter_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='reject',
        ),
    ]
