# Generated by Django 4.2.14 on 2024-07-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0006_remove_booking_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='accept',
            field=models.BooleanField(),
        ),
    ]
