# Generated by Django 4.2.14 on 2024-07-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0007_alter_booking_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
    ]
