# Generated by Django 4.2.14 on 2024-07-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
